name: backports

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global user.name gha
          git config --global user.email actions@github.com
          git push
